FROM python:3.9-slim-bullseye
COPY . /binance
WORKDIR /binance
RUN python3 -m pip install -r requirements.txt
ENTRYPOINT ["python3", "-m", "binance.collector"]
CMD ["python3", "-m", "binance.collector", "--help"]